### ISSUE TITLE
Knob indicator doesn't adjust when its `value` prop is modified though a callback

### ISSUE THREAD

**Issue by Bachibouzouk** [plotly/dash-daq#11]
The title should be explicit enough, here are the callback and the visuals

```
@app.callback(
    Output('knob', 'value'),
    [],
    [],
    [
        Event('radio-choice', 'change')
    ]
)
def knob_reset():
    """reset the knob to 0 when the radio item is toggled"""
    return 0
```

![2017-07-09_knob_value_norm](https://user-images.githubusercontent.com/4399407/42437572-cbbe5640-835d-11e8-9fef-bd5c6b0e8da8.png)

![2017-07-09_knob_value_err](https://user-images.githubusercontent.com/4399407/42437577-cefe572e-835d-11e8-92fc-1634685995ba.png)

**Comment by Karan-S-Mittal** [comment]
here's a preview. the knob's value is being set to a certain value with change in boolean switch.




https://user-images.githubusercontent.com/41485085/139593594-32198cf1-6d6f-44c1-9d56-fe7c156ee46f.mov
