### ISSUE TITLE
julia version

### ISSUE THREAD

**Issue by shashi** [plotly/dash-daq#114]
would be awesome!!!

**Comment by jackparmer** [comment]
It's coming :) We need to get the 1.0 release of https://github.com/plotly/Dash.jl out first.

For anyone interested in doing this, https://github.com/plotly/Dash.jl/issues/11 shows the way there.

**Comment by jackparmer** [comment]
This exists now: https://dash-julia.plotly.com/dash-daq

**Comment by shashi** [comment]
Haha indeed!! :tada:
