### ISSUE TITLE
daq.Gauge prop 'showCurrentValue' value is misaligned without 'label' property also

### ISSUE THREAD

**Issue by wbrgss** [plotly/dash-daq#123]
Running the "Current Value and Units" section example from the Dash DAQ [Gauge chapter](https://dash.plotly.com/dash-daq/gauge) and omitting the `label` property results in a very misaligned current value:

![image](https://user-images.githubusercontent.com/9068290/95519797-db5bc880-0993-11eb-81e0-12e945e226d5.png)

With the `label` argument provided:

![image](https://user-images.githubusercontent.com/9068290/95520172-b1ef6c80-0994-11eb-93e7-225ec3ee4059.png)

***

The current value is centered relative to the viewport instead of the component, I suspect because it's missing the flex rules in the direct child of the outermost `.daq-gauge--light` container (applied to a hashed styled-components class, but also using the `daq-gauge--light__label` class). This `.daq-gauge--light__label`, `<div>` container is missing its `class` attributes when there is no `label` prop provided to `daq.Gauge` (although the `<div>` element itself is there either way).

It makes sense to have use cases that display the `currentValue` property without the `label` property.

Minimal example:

```py
import dash
import dash_daq as daq
import dash_html_components as html

app = dash.Dash(__name__)

app.layout = html.Div([
    daq.Gauge(
        showCurrentValue=True,
        # label="Default", # uncomment to have normal "currentValue" alignment
        value=6
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by Chambana** [comment]
Still broken as of 1.21.  

Temporary workaround is to add a label string containing a single space in it (e.g. " ") to each gauge
