### ISSUE TITLE
daq.Gauge does not display interval labels with non-0 integer 'min' prop value

### ISSUE THREAD

**Issue by wbrgss** [plotly/dash-daq#124]
I think the labels should be displayed, with the interval count simply starting at `min` as I think is implied by the `scale` prop description/[docstrings](https://dash.plotly.com/dash-daq/gauge) (see "Gauge properties"). The `scale` arguments (e.g. `labelInterval`) appear to be directly related to the label display.

> scale (dict; optional): Configuration for the component scale. scale has the following type: dict containing keys 'start', 'interval', 'labelInterval', 'custom'. Those keys have the following types:
>  + start (number; optional): Value to start the scale from. Defaults to **min**.

Providing a non-`0` (EDIT: positive) max value does not affect the interval label display, which is inconsistent IMO.

With a non-`0` `min` (EDIT: positive) argument — no interval labels:

![image](https://user-images.githubusercontent.com/9068290/95522331-d3068c00-0999-11eb-8956-f8b1add9493a.png)

When the `min` value is `0`, either implicitly (by default) or explicitly with `min=0`:

![image](https://user-images.githubusercontent.com/9068290/95522480-3c869a80-099a-11eb-9fe0-720607c8d20d.png)

Minimal example: 

```py
import dash
import dash_daq as daq
import dash_html_components as html

app = dash.Dash(__name__)

app.layout = html.Div([
    daq.Gauge(
        min=1,
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by n304win** [comment]
can confirm!

**Comment by Yakult182** [comment]
Colors also don't align with the range-values if min is not equal to zero. In the following example I would expect the gauge to be around the green range at 22. Missing labels due to the known bug. 
``` python
 daq.Gauge(
                     color={"gradient":True ,"ranges":{"#ff0001": [16, 20], "FFFF00":[20, 21], "green": [21, 22], "yellow" : [22,26], "#FF0000":                     [26,30] }},
                     value=22,
                     label='Default',
                     scale={'interval': 2, 'labelInterval': 2},
                     max=30,
                     min=16,
                     )

![image](https://user-images.githubusercontent.com/64208030/101114903-b3c75c00-35e2-11eb-823d-7cdf438662c0.png)

**Comment by inviridi** [comment]
Odd behaviour. Unfortunately, it renders gauges pretty useless for me.

**Comment by Karan-S-Mittal** [comment]
> Colors also don't align with the range-values if min is not equal to zero. In the following example I would expect the green area to be around the gauge needle at 22. Missing labels due to the known bug.
> 
> ```python
>  daq.Gauge(
>                      color={"gradient":True ,"ranges":{"#ff0001": [16, 20], "FFFF00":[20, 21], "green": [21, 22], "yellow" : [22,26], "#FF0000":                     [26,30] }},
>                      value=22,
>                      label='Default',
>                      scale={'interval': 2, 'labelInterval': 2},
>                      max=30,
>                      min=16,
>                      )
> ```
> 
> ![2020-12-04 03_43_17-Dash — Mozilla Firefox](https://user-images.githubusercontent.com/64208030/101115719-1b31db80-35e4-11eb-959b-c3a35d4e15f3.png)

Hey @Yakult182,
In your code, you have actually not added 2nd color property properly. I am working on this bug fix and was using your code but the color behavior was working correctly. I am adding a GIF that has the issue corrected. will create a PR soon as the original bug is resolved as well.
![issue-124](https://user-images.githubusercontent.com/41485085/131555582-c2f48282-4a84-41c2-9866-48a18cb539be.gif)
