### ISSUE TITLE
Boolean switch indicates there is a size prop in documentation, but prop isn't listed.

### ISSUE THREAD

**Issue by matthewchan15** [plotly/dash-daq#15]
The boolean switch in the documentation says there is a size prop, but when attempting to use this prop with the component, it's clear that this prop is missing.

``` Python
TypeError: Unexpected keyword argument `size`
Allowed arguments: className, color, disabled, id, label, labelPosition, on, style, theme, vertical
```
![booleanswitch](https://user-images.githubusercontent.com/33464965/42894874-5365bf84-8a75-11e8-9782-6a9aa5f9f22f.JPG)

**Comment by shammamah** [comment]
Closed (added correct props to Dash Docs for all Dash DAQ components).
