### ISSUE TITLE
Error loading dependencies

### ISSUE THREAD

**Issue by evafast** [plotly/dash-daq#25]
Hi, I am getting the following error when I try to deploy one of your dash-daq graphs using heroku. I am using python 3, I listed my other installed packages below. I also installed dash-daq with pip3.
Let me now if you have any suggestions on how to fix this.

Thanks!

Eva

certifi==2018.11.29
chardet==3.0.4
Click==7.0
dash==0.36.0
dash-core-components==0.43.0
dash-daq==0.1.0
dash-html-components==0.13.5
dash-renderer==0.17.0
decorator==4.3.2
Flask==1.0.2
Flask-Compress==1.4.0
gunicorn==19.9.0
idna==2.8
ipython-genutils==0.2.0
itsdangerous==1.1.0
Jinja2==2.10
jsonschema==2.6.0
jupyter-core==4.4.0
MarkupSafe==1.1.0
nbformat==4.4.0
numpy==1.16.0
pandas==0.24.0
plotly==3.5.0
python-dateutil==2.7.5
pytz==2018.9
requests==2.21.0
retrying==1.3.3
scikit-learn==0.20.2
scipy==1.2.0
six==1.12.0
traitlets==4.3.2
urllib3==1.24.1
Werkzeug==0.14.1

**Comment by itcarroll** [comment]
Me too. This is what I see in Chrome:

```
GET https://unpkg.com/dash_daq@0.1.0/dash_daq/bundle.js 404
```

Are we supposed to serve bundle.js locally, requiring local build, pain, and suffering?

**Comment by shammamah** [comment]
You need to add the following line to your app code, if you don't already have it: 

```
app.scripts.config.serve_locally = True
```

If that doesn't work, please send me a link to your code!

**Comment by evafast** [comment]
This worked! Thank you so much - very helpful!!!

**Comment by shammamah** [comment]
@evafast @itcarroll Just wanted to update you guys -- the latest version `dash-daq 0.1.1` is published on NPM, so there is no longer any need to add the line  `app.scripts.config.serve_locally = True`.

**Comment by itcarroll** [comment]
Thanks for the heads up, but I'm not getting it working yet. I do see
dash-daq published on npmjs, but when I run an app (with version 0.1.2), I
get the same error and see in the Chrome console:
```
GET https://unpkg.com/dash_daq@0.1.2/dash_daq/bundle.js 404
```
I don't understand/see where the server is defined or configured.

**Comment by itcarroll** [comment]
Ah, shouldn't it be <https://unpkg.com/dash-daq@0.1.2/dash_daq/bundle.js>, with a hyphen not an underscore?

**Comment by shammamah** [comment]
@itcarroll Yes, good catch! We're still getting some odd issues with the NPM package -- for now, I recommend just using version `0.1.1` with `app.scripts.config.serve_locally` set to `True`. Sorry about that! I'll reopen the issue in the meantime.

**Comment by shammamah** [comment]
New release `0.1.4` should solve this issue. Let me know if it doesn't work out!
