### ISSUE TITLE
DAQ is not published on NPM

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-daq#28]
Contrary to other component repos for dash, daq is not published on NPM, which forces the use of `app.scripts.config.serve_locally = True` and prevents it from workinf with the default dash configuration.

It should be published like other packages :)

Original community issue [here](https://community.plot.ly/t/cannot-run-dash-daq-example-loading-error/19508)

Relates to https://github.com/plotly/dash-daq/issues/25

**Comment by shammamah** [comment]
Closed by #30
