### ISSUE TITLE
gauge custom scale not applying style

### ISSUE THREAD

**Issue by sdementen** [plotly/dash-daq#40]
I am using a DAQ gauge as following
```
daq.Gauge(
            color={"gradient": True, "ranges": {"green": [0, 5], "yellow": [5, 7], "red": [7, 9], "black": [9, 10]}},
            value=2,
            max=10,
            min=0,
            scale={
                "custom": {
                    0.14: {"style": {"color": "red"}, "label": "Hello"},
                    4.14: {"style": {"color": "red"}, "label": "Foo"},
                    4.95: {"style": {"color": "red"}, "label": "Baz"},
                    8.12: {"style": {"color": "red"}, "label": "Jeez<br>bom"},
                }
            },
        ),
```
and I have the issues:
- style instruction is in the dom but has no effect (ie, text is not red)
`<text x="118.58641410998341" y="64.01665418691996" text-anchor="middle" style="color: red;">Baz</text>`
- the <br> is escaped

If style did work, would it be possible to have the text of the scale outside the gauge instead of inside ?

**Comment by jdyerrhg** [comment]
I ran into this issue too and just came across this post.  After some playing around, I figured out you need "fill" instead of "color" in your custom scale styles.

**Comment by Karan-S-Mittal** [comment]
as mentioned by @jdyerrhg, this will be your solution. I have modified some colors 
## Output

![chrome_aAfsu474L0](https://user-images.githubusercontent.com/41485085/135334086-aa636c14-fe93-42f9-b13d-28cc7745a0db.png)

## Code
```Python
daq.Gauge(
            color={"gradient": True, "ranges": {"green": [0, 5], "yellow": [5, 7], "red": [7, 9], "black": [9, 10]}},
            value=2,
            max=10,
            min=0,
            scale={
                "custom": {
                    0.14: {"style": {"fill": "red"}, "label": "Hello"},
                    4.14: {"style": {"fill": "turquoise"}, "label": "Foo"},
                    4.95: {"style": {"fill": "blue"}, "label": "Baz"},
                    8.12: {"style": {"fill": "red"}, "label": "Jeez<br>bom"},
                }
            },
        ),
```
