### ISSUE TITLE
demo.py is not compatible with dash-0.40

### ISSUE THREAD

**Issue by anhinga** [plotly/dash-daq#43]
`Event` disappeared from https://github.com/plotly/dash/blob/master/dash/dependencies.py

so one gets this diagnostics:

>python demo.py
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from dash.dependencies import Input, Output, State, Event
ImportError: cannot import name 'Event' from 'dash.dependencies' (C:\ProgramData\Anaconda3\lib\site-packages\dash\dependencies.py)

**Comment by anhinga** [comment]
actually, events were removed in this Jan 7 commit:

https://github.com/plotly/dash/commit/2ed3989256251114b23bf37c00ec2c60d2e76ff2#diff-1b30af980419a25a5ffd5fdfc4ef0173

So, it's much earlier than dash 0.40, it's not working for a while...

**Comment by shammamah** [comment]
@anhinga Thanks for bringing this to our attention! Please check out the PR above and let me know if it is working for you.

**Comment by anhinga** [comment]
@shammamah Works for me - thanks!!!
