### ISSUE TITLE
Color not Dash Output type 

### ISSUE THREAD

**Issue by matthijsramlab** [plotly/dash-daq#44]
The color option is not a Dash Output type. I would like to change the color of the switch depending on the user input. Should I instead use the theme parameter? 

The error message I got:

dash.exceptions.IncorrectTypeException: The output argument `stop_know.color` is not of type `dash.Output`.

My component:

daq.ToggleSwitch(id='stop_know', value=False, color="#FF5E5E")

**Comment by shammamah** [comment]
Hey @matthijsramlab! Would you be able to post the code that you're using?

**Comment by matthijsramlab** [comment]
Hi, you can close the issue. I made a stupid mistake...

@app.callback(
		[
			State('stop_know', 'color'),
			State('stop_at_bead', 'color'),
			State('stop_at_layer', 'color'),
		],
		[
			Input('dio_updater', 'n_intervals')
		],
		[
			State('stop_know', 'value'),
			State('stop_at_bead', 'value'),
			State('stop_at_layer', 'value'),
			State('robot_name', 'children')
		]
	)

Instead of setting them as a Output, I typed State....

**Comment by shammamah** [comment]
Glad you figured it out :)
