### ISSUE TITLE
daqNumericInput is not compatible with Dark Theme

### ISSUE THREAD

**Issue by CanerIrfanoglu** [plotly/dash-daq#55]
`daqNumericInput ` remains white on dark mode. Inside text is converted to white. This results white input on white background hence not readable. Please see below a reproducible R example and associated screenshots.

```r
library(dash)
library(dashDaq)
library(dashHtmlComponents)

app <- Dash$new()

theme <- list(
  'dark' = TRUE,
  'detail' = '#007439',
  'primary' = '#00EA64',
  'secondary' = '#6E6E6E'
)

rootLayout <- htmlDiv(list(
  daqLEDDisplay(value = "3.14159"),
  htmlBr(),
  daqNumericInput(min = 0, max = 10, value = 4),
  htmlBr(),
  daqPowerButton(on = TRUE)
))

app$layout(htmlDiv(
  list(daqDarkThemeProvider(theme = theme,
                            children = rootLayout)),
  style = list('backgroundColor' = '#303030',
                     'float' = 'left')
))

app$run_server(port = 8897)
```

<img width="242" alt="Screen Shot 2019-07-10 at 2 38 39 PM" src="https://user-images.githubusercontent.com/20918264/60995421-7cd31500-a320-11e9-9c8f-fb914959a8ff.png">
<img width="241" alt="Screen Shot 2019-07-10 at 2 38 49 PM" src="https://user-images.githubusercontent.com/20918264/60995428-7fce0580-a320-11e9-99a6-6fe214ab37ad.png">

**Comment by ycaokris** [comment]
This bug also exists on python side, example on dash-docs https://dash.plot.ly/dash-daq/darkthemeprovider showed a white text color on darktheme.

<img width="896" alt="Screen Shot 2019-07-11 at 11 05 12 AM" src="https://user-images.githubusercontent.com/35306149/61062213-c62c6e80-a3cb-11e9-9de2-4e82ce480853.png">
